### ISSUE TITLE
Item Frame item name display problem

### ISSUE THREAD

**Issue by Ummio** [steve4744/WhatIsThis#10]
When do I support renamed names for items in the Item Frame
And too close is not the content of the Item Frame,but the block behind
![image](https://github.com/steve4744/WhatIsThis/assets/85783168/bc2c70a2-f0ae-4624-80cf-facbd346b922)

**Comment by steve4744** [comment]
Both issues should be fixed in the 5.5-SNAPSHOT build. Thanks.
