### ISSUE TITLE
Slimefun Update

### ISSUE THREAD

**Issue by Hellcode48** [steve4744/WhatIsThis#3]
This plugin needs to update its slimefun dependency, its over 30 builds behind

**Comment by steve4744** [comment]
I presume you mean slimefun dev builds, as RC-18 is the latest release on GitHub, and this plugin used RC-17. Unless the API has changed and/or something is broken there's no need to update the plugin dependency with every dev update.

Having said that I'll update it to RC-18 in the next few days. 
Thanks.

**Comment by Hellcode48** [comment]
You do not want to use recommended, even the slimefun main dev said not to, even if its stable its not stable. Always use dev builds, they are more up-to-date

**Comment by Hellcode48** [comment]
https://i.imgur.com/BjNG73u.png

**Comment by steve4744** [comment]
That's good advice for a server owner but is not relevant. I use the BlockStorage#check() method from Slimefun. If that method doesn't change, there is little point up re-compiling and making a new release of this plugin every time a dev release is made. 

Also this is compiled using Maven, and the Slimefun dev doesn't put the dev builds on Maven to be used - there is nothing available between RC-17 and RC18 on Jitpack:
![image](https://user-images.githubusercontent.com/6975392/103323664-eaef2880-4a3b-11eb-8868-f6a74edfbe8d.png)

Hope that makes sense. 

If there is something not working or you have found an issue with this current version please let me know and I'll happily try to fix it.

**Comment by Hellcode48** [comment]
I honestly just know from my own experience that the latest builds make my plugin work properly (by using the actual jar rather than maven method lol), also I didn't know slimefun itself had a maven repo (I should have thought of that but I just didn't. I will close this issue if the latest build of WhatIsThis works with latest dev of slimefun

**Comment by steve4744** [comment]
Hopefully it does, but I don't know Slimefun from a players view, so my testing is very basic.  I'm reliant on people finding and reporting any issues they find.

**Comment by TheBusyBiscuit** [comment]
> That's good advice for a server owner but is not relevant. I use the BlockStorage#check() method from Slimefun. If that method doesn't change, there is little point up re-compiling and making a new release of this plugin every time a dev release is made.

Correct! The advice is targeted towards server owners, not developers.
The RC-versions are specifically designed to serve as API "landmarks", so it is absolutely safe to use them for hooking into the plugin, that is pretty much their main purpose, so no worries about that.
The API will slightly change whenever a new RC is released.
But given the way how WhatIsThis integrates it, the API should remain pretty much the same unless a major rewrite of these methods happens.
I don't see any reason why there'd be issues now or anytime soon.
