### ISSUE TITLE
Custom Block names stop showing with larger amount of plugins in use

### ISSUE THREAD

**Issue by kencinder** [steve4744/WhatIsThis#6]
I spent several hours chasing my tail over what was causing this, and it appears as soon as I hit 49+ plugins, custom block names will no longer show.
I can remove ANY 2 plugins out of the 50 I am running, and custom block names will show again.

I started removing the first 2 plugins in this list, works. Then put them back and removed AsyncWorldEdit and Worldedit, works. Put worldedit back, doesn't work. Put either of the first two back, doesn't work.

Perhaps it has something to do with the size/length of the classpath with this many plugins? I didn't test every combination of removing plugins to hit 48 plugins.

Plugin List
```
AlchimiaVitae
AppleCoreSpigot
AsyncWorldEdit
BungeeTabListPlus
ChestSort
Chunky
ChunkyBorder
CrystamaeHistoria
DeluxeMenus
DiscordSRV
DoorsReloaded
DyedBackpacks
DynaTech
EcoPower
ElectricSpawners
ExoticGarden
ExtraGear
ExtraTools
FancyWaystones
FlowerPower
FluffyMachines
FoxyMachines
Galactifun
GDHooks
Graves
GriefDefender
Gringotts
LiteXpansion
LuckPerms
LumberJack
MobCapturer
Networks
Nova
PlaceholderAPI
ProtocolLib
RealCompass
SensibleToolbox
SimpleStorage
Slimefun
SlimefunOreChunks
SlimeTinker
SlimyTreeTaps
SoulJars
squaremap
Vault
VentureChat
WhatIsThis
WorldEdit
```

**Comment by steve4744** [comment]
Interesting......I have no idea why the number of plugins would make any difference unless its a server resource issue, or possibly some clash with another plugin.
I currently have 52 plugins on my test server which doesn't have an issue displaying Nova and Slimefun blocks.

OK, so some questions:

What version of Minecraft and WhatIsThis are you running?

Do you have 'auto-display' enabled?
If so, does it still fail if 'auto-display' is off when using the /wt command and/or right-clicking the block?

When it fails, are there any errors in the console at that point or during startup? If so, please supply the whole log.
Which display method fails, or is it all of them (scoreboard, bossbar, actionbar, chat)?

When it fails for custom blocks does it still work for normal Minecraft blocks?

Hopefully we can eliminate some things and find out what's going on.
Thanks.

**Comment by kencinder** [comment]
My bad, I should know better and usually post that info.

Server: Paper 1.18.1-212
WhatIsThis 4.7 (First thing I tried was 4.6 and 4.5...no difference)

Auto display is enabled on my production server, where we only use Boss Bar display.

On my test server I left things at the defaults, auto display off with the stick showing info in the action bar and scoreboard.

Occurs on both until I get my plugin count down to 48 out of the 50 I am running.

There are no errors in the console, and nomal blocks still display fine, only Custom Blocks from Nova and Slimefun+Addons are affected.

**Comment by steve4744** [comment]
I downloaded maybe all of the slimefun addons you have in your list. My test-server now has 70 plugins and is also running paper-212, and I'm not seeing any issues with custom blocks.

![2022-02-24_16 48 57](https://user-images.githubusercontent.com/6975392/155570781-2f21a0be-1cce-4924-ab30-b692d2d60a9f.png)

![2022-02-24_16 52 35](https://user-images.githubusercontent.com/6975392/155570824-be714c4b-aeb1-402a-87ea-f7aacb39bfa5.png)

So at the moment I don't think its a problem with the plugin, as the number of plugins on the server has no effect, and there are no errors generated to indicate the plugin is failing in any way.

**Comment by kencinder** [comment]
I'm totally stumped on finding what is causing it then, no matter what plugins I keep in or remove, no specific one causes it to happen.

**Comment by steve4744** [comment]
I downloaded the other non-premium plugins in your list and was able to recreate the issue.
For me, the only time the issue occurred when when I had gringotts installed. No idea why although its not officially supported on 1.18
Could you try removing gringotts and see if that works for you.

**Comment by kencinder** [comment]
I swore I had pulled every single plugin out one by one, but I just took gringotts out lo and behold, there is no issue with the other plugins.
I don't even understand how this happens. With gringotts in, custom blocks show fine until I hit 49 of the plugins I use. Remove any two, problem is gone.

**Comment by steve4744** [comment]
What's happening is with >48 plugins (including Gringotts) the load order is getting changed, so that although Nova and Slimefun are soft-depends for WhatIsThis, they are being loaded after WhatIsThis, so its not aware of those plugins or custom blocks.

Without Gringotts the number of plugins makes no difference.

Gringotts has an outstanding issue (https://github.com/nikosgram/gringotts/issues/84) which is very similar to this one, and  includes a workaround which seems to fix the problem.

**Comment by kencinder** [comment]
Problem is, Vault is already in softdepend in gringotts 2.12.2

nvm it's in both...I see what that issue is saying

Doing that does fix the problem. Thank you for helping dig into what was causing this.

**Comment by steve4744** [comment]
No problem. Closing as its not an issue with this plugin.
