### ISSUE TITLE
[Feature Request] See what an item is inside of an item frame?

### ISSUE THREAD

**Issue by AE720** [steve4744/WhatIsThis#9]
Feel free to close this if it's not possible to do in a plugin, but it would be really nice to see what an item that is currently framed is. I think it's possible with an execute command but I don't know how feasible it is to run that and parse it's information like that. Currently it just tells you it's an item frame.

**Comment by steve4744** [comment]
Thanks for the suggestion. I'll add it in the next update.

**Comment by steve4744** [comment]
This was added in version 5.4, commit ca04aec
